# Generated by Django 5.1 on 2024-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmi', '0002_alter_redmi_options_alter_redmi_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redmi',
            name='sim_card',
            field=models.CharField(choices=[('O!', 'O!'), ('BEELINE', 'BEELINE'), ('Mega com', 'Mega com')], default=1, max_length=10, verbose_name='Sim_card'),
            preserve_default=False,
        ),
    ]
