# Generated by Django 5.1 on 2024-09-07 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redmi', '0004_xiaomi_alter_redmi_options_comment_redmi_xiaomi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='redmi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redmi', to='redmi.redmi'),
        ),
        migrations.RemoveField(
            model_name='redmi',
            name='xiaomi',
        ),
        migrations.DeleteModel(
            name='Xiaomi',
        ),
    ]
