# Generated by Django 5.1 on 2024-09-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redmi', '0005_alter_comment_redmi_remove_redmi_xiaomi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
